---

- name: start apache
  service:
    name: apache2
    state: started
    
- name: restart apache
  service:
    name: apache2
    state: restarted

- name: reload apache
  command: service apache2 graceful

- name: activate apache configuration
  file: 
    src: "{{ item.dest }}"
    dest: "/etc/apache2/conf-enabled/{{ item.item }}.conf"
    owner: root
    group: root
    state: link
  loop: "{{ conf_created.results|flatten(levels=1) }}"
  when: item.changed

- name: activate apache site
  file: 
    src: "{{ item.dest }}"
    dest: "/etc/apache2/sites-enabled/{{ item.item }}.conf"
    owner: root
    group: root
    state: link
  with_items: "{{ sites_created.results }}"
#  loop: "{{ sites_created.results|flatten(levels=1) }}"
#  when: item.changed
  
- name: activate apache module
  file: 
    src: "{{ item.dest }}"
    dest: "/etc/apache2/mods-enabled/{{ item.item }}.conf"
    owner: root
    group: root
    state: link
  loop: "{{ mods_created.results|flatten(levels=1) }}"
  when: item.changed
 
