---

- name: start apache
  service:
    name: apache2
    state: started
    
- name: restart apache
  service:
    name: apache2
    state: restarted

- name: reload apache
  command: systemctl reload apache2

- name: activate apache configuration
  command: a2enconf {{ item }}
  when: item.changed
  with_items: conf_created.results

- name: activate apache site
  command: a2ensite {{ item }}
  when: item.changed
  with_items: sites_created.results

- name: activate apache module
  command: a2enmod {{ item }}
  when: item.changed
  with_items: mods_created.results