---

- name: Ensure PHP-FPM is installed
  package:
    name: php-fpm
    state: present

- name: debug the variable
  debug:
    var: phpfpm_max_children


- name: Ensure pool config is in place
  template:
    src: www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  when: phpfpm_www_conf.stat.size > 100
