---

- name: Ensure Apache is installed
  package:
    name: apache2
    state: present
    
#- name: Ensure mod_deflate settings are active
#  template:
#    src: gzip.conf.j2
#    dest: /etc/apache2/conf-available/gzip.conf
#    mode:  0644
#    owner: root
#    group: root

# FIXME: every time we add configs to the templates dir, we will have to add it to 
# the "loop" list here. Is there a way to loop based on everything in the templates dir?

- name: build directory structure for vhost
  file:
    state: directory
    path: "/var/www/vhosts/{{domain}}"
    owner: root
    group: root
    mode: 0755
  
- name: Ensure apache configs are active
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/apache2/conf-available/{{ item }}.conf"
    mode:  0644
    owner: root
    group: root
    backup: true
  register: conf_created
  loop:
    - gzip
    - "php{{php_vers}}-fpm"
  notify: 
   - activate apache configuration
   - reload apache

- name: Ensure apache module configs are active
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/apache2/mods-available/{{ item }}.conf"
    mode:  0644
    owner: root
    group: root
    backup: true
  register: mods_created
  loop:
    - ssl
  notify: 
    - activate apache module
    - restart apache

- name: Ensure apache modules are active 
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy_fcgi
    - ssl
  notify:
    - restart apache
  
- name: Ensure apache sites are active
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
    mode:  0644
    owner: root
    group: root
    backup: true
  register: sites_created
  loop:
    - vhost
  notify: 
   - activate apache site
   - reload apache


#- name: Debug the variable
#  debug:
#    var: sites_created
  