---

- name: apply common configuration to all nodes
  hosts: all
  become: yes
  vars_files:
    - defaults.yml

  roles:
    - common
    - mariadb
    - redis
    - php-fpm
    - apache
    - magento
    - varnish
    - iptables

#  tasks:
#    - name: Display all variables/facts known for a host
#      debug:
#        var: hostvars[inventory_hostname]
