---

- name: Ensure that varnish is installed
  package:
    name: varnish
    state: present

- name: Ensure varnish is enabled and starts on boot
  systemd:
    name: varnish
    state: started
    enabled: yes


