---

- name: Ensure mariadb packages are installed
  package:
    name: "{{item}}"
    state: present
  loop:
    - mariadb-server
    - python-mysqldb

- name: Ensure MariaDB is enabled and starts on boot
  systemd:
    name: mariadb
    state: started
    enabled: yes
    
# Note: we don't change root's password because Ubuntu uses 
# socket-based auth for the root MySQL password user.
# in other words, the system root user can login to MySQL without a password
# but other system users cannot login as MySQL root user.

- name: Remove anonymous users a la mysql_secure_installation
  mysql_user:
   name: ''
   host_all: yes
   state: absent

- name: Remove test db
  mysql_db:
      name: test
      state: absent

- name: Create Magento database
  mysql_db:
      name: magento_db
      state: present

- name: Assign random password for Magento database user
  set_fact:
    magento_db_password: "{{ lookup('password', '~/magento_db_creds chars=ascii_letters,digits length=36')}}"

- name: Ensure Magento2 database user is present with proper permissions
  mysql_user:
    login_user: root
    check_implicit_admin: yes
    name: magento_db
    password: "{{ magento_db_password }}"
    priv: "magento_db.*:DROP,LOCK TABLES,SELECT,INSERT,INDEX,ALTER,CREATE TEMPORARY TABLES,UPDATE,CREATE,DELETE"
    host: localhost
    update_password: on_create

- name: Tune system for MariaDB
  include: system_tuning.yml
  when: mysql_system_tuning