---

- name: Create PHP-FPM Group
  group:
    name: "{{ magento_os_group}}"
    state: present

- name: Create Magento user
  user:
    name: "{{ magento_os_user }}"
    groups: "{{ magento_os_group}}"
    append: yes
    home: "{{ item.home | default(omit, true) }}"
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation')  | password_hash('sha512')}}"
    update_password: on_create
