---

- name: Ensure Magento group exists
  group:
    name: "{{ magento_os_group}}"
    state: present

- name: Ensure Magento user exists
  user:
    name: "{{ magento_os_user}}"
    groups: "{{ magento_os_group | default(omit, true) }}"
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation')  | password_hash('sha512')}}"
    update_password: on_create
